### ISSUE TITLE
JSON decode error

### ISSUE THREAD

**Issue by seifreed** [a0rtega/metame#13]
After the latest radare update I'm getting:

```
[INFO] Opening file with r2
Traceback (most recent call last):
  File "/usr/local/bin/metame", line 5, in <module>
    metame.main()
  File "/usr/local/lib/python2.7/dist-packages/metame/__init__.py", line 19, in main
    r = r2parser.R2Parser(args.input, True, debug=args.debug, force_replace=args.force)
  File "/usr/local/lib/python2.7/dist-packages/metame/r2parser.py", line 21, in __init__
    if not info["bin"]["bits"] in constants.supported_bits or \
KeyError: 'bin'
[INFO] Opening file with r2
[INFO] Analyzing functions with r2
[INFO] Loading functions information
Traceback (most recent call last):
  File "/usr/local/bin/metame", line 5, in <module>
    metame.main()
  File "/usr/local/lib/python2.7/dist-packages/metame/__init__.py", line 20, in main
    patches = r.iterate_fcn()
  File "/usr/local/lib/python2.7/dist-packages/metame/r2parser.py", line 35, in iterate_fcn
    fcns = json.loads(self.r2.cmd("aflj"))
  File "/usr/local/lib/python2.7/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

This happens with any binary used

**Comment by a0rtega** [comment]
This issue has been fixed in the latest release.
