### ISSUE TITLE
What's the problem

### ISSUE THREAD

**Issue by playplaya** [a0rtega/metame#16]
root@XS4325421825:/var/uuu# metame -i ups.exe -o s.exe             
[INFO] Opening file with r2
[INFO] Analyzing functions with r2
Traceback (most recent call last):
  File "/usr/local/bin/metame", line 5, in <module>
    metame.main()
  File "/usr/local/lib/python2.7/dist-packages/metame/__init__.py", line 20, in main
    patches = r.iterate_fcn()
  File "/usr/local/lib/python2.7/dist-packages/metame/r2parser.py", line 34, in iterate_fcn
    arch = x86handler.X86Handler(self.bits, self.debug, self.force)
  File "/usr/local/lib/python2.7/dist-packages/metame/x86handler.py", line 73, in __init__
    ks_mode = KS_MODE_32 if self.bits == 32 else KS_MODE_64
NameError: global name 'KS_MODE_32' is not defined
root@XS4325421825:/var/uuu# metame --help          

THE File is winx86

**Comment by gogo2464** [comment]
from the doc extension, the program might work exclusively on windot https://github.com/a0rtega/metame?tab=readme-ov-file#usage

**Comment by gogo2464** [comment]
ah no you forgot to install keyston dependency
