### ISSUE TITLE
Radare 2? Somebody said Binary too big..

### ISSUE THREAD

**Issue by Vendorss** [a0rtega/metame#18]
Does having too big a binary cause problems?

C:\Users\faker\AppData\Local\Programs\Python\Python38\Scripts>python metame -i Coinbase.exe -o Wallet.exe -d
[INFO] Opening file with r2
Traceback (most recent call last):
  File "C:\Users\faker\AppData\Local\Programs\Python\Python38\lib\site-packages\r2pipe\open_sync.py", line 64, in __init__
    self.process = Popen(
  File "C:\Users\faker\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\faker\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "metame", line 5, in <module>
    metame.main()
  File "C:\Users\faker\AppData\Local\Programs\Python\Python38\lib\site-packages\metame\__init__.py", line 19, in main
    r = r2parser.R2Parser(args.input, True, debug=args.debug, force_replace=args.force)
  File "C:\Users\faker\AppData\Local\Programs\Python\Python38\lib\site-packages\metame\r2parser.py", line 19, in __init__
    self.r2 = r2pipe.open(filename, flags)
  File "C:\Users\faker\AppData\Local\Programs\Python\Python38\lib\site-packages\r2pipe\open_sync.py", line 68, in __init__
    raise Exception("ERROR: Cannot find radare2 in PATH")
Exception: ERROR: Cannot find radare2 in PATH

**Comment by bekojuniranjan** [comment]
I have faced the same issue. The issue is that you need to install the radare2

To install radare2 from source

```
git clone https://github.com/radareorg/radare2
cd radare2 
sys/install.sh
```
