### ISSUE TITLE
ImportError: ERROR: fail to load the dynamic library.

### ISSUE THREAD

**Issue by Alexxino** [a0rtega/metame#5]
Running under VM Linux Kali updated:
Radare2 - installed.
r2pipe - installed.
keystone-engine - installed.

When I try to run it i have this:

`Traceback (most recent call last):
  File "/usr/local/bin/metame", line 5, in <module>
    metame.main()
  File "/usr/local/lib/python3.5/dist-packages/metame/__init__.py", line 5, in main
    import metame.r2parser as r2parser
  File "/usr/local/lib/python3.5/dist-packages/metame/r2parser.py", line 2, in <module>
    import metame.x86handler as x86handler
  File "/usr/local/lib/python3.5/dist-packages/metame/x86handler.py", line 6, in <module>
    from keystone import *
  File "/usr/local/lib/python3.5/dist-packages/keystone/__init__.py", line 4, in <module>
    from .keystone import Ks, ks_version, ks_arch_supported, version_bind, debug, KsError, __version__
  File "/usr/local/lib/python3.5/dist-packages/keystone/keystone.py", line 75, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.
`

I tried with python2.7 and python3.5.

**Comment by a0rtega** [comment]
There is an error with your keystone installation.

Try using the following command:

`$ sudo ldconfig`

If it doesn't work, try downloading it from the [official website](http://www.keystone-engine.org/) and install the library and the python bindings following the [instructions](https://github.com/keystone-engine/keystone/blob/master/docs/COMPILE-NIX.md).
