### ISSUE TITLE
Error after installing everything right

### ISSUE THREAD

**Issue by whiteworthy** [a0rtega/metame#7]
I installed everything 2 times and it still gives me this error:

ubuntu@ip-172-31-9-203:~/metame$ metame -i test.exe -o penmut.exe
[INFO] Opening file with r2
Traceback (most recent call last):
  File "/usr/local/bin/metame", line 5, in <module>
    metame.main()
  File "/usr/local/lib/python3.5/dist-packages/metame/__init__.py", line 19, in main
    r = r2parser.R2Parser(args.input, True, debug=args.debug, force_replace=args.force)
  File "/usr/local/lib/python3.5/dist-packages/metame/r2parser.py", line 21, in __init__
    if not info["bin"]["bits"] in constants.supported_bits or \

**Comment by whiteworthy** [comment]
fixed it by itself, i don't know how. Metame still works if anyone is wondering.
